title: Caleb Winters
year: 2014

content: |
  A portfolio site for sound designer and composer [Caleb Winters](http://calebwinters.ca).
  Generous whitespace, along with a relatively flat informational hierarchy and a distinctive geometric sans-serif helped form a quirky-yet-mature atmosphere around Caleb's work.
  Fluid transitions between pages allows for quicker navigation of the site and helps reflect the cinematic nature of his work. Both of these aspects were vital when applying to sound production studios where applicants have only a short timeframe to impress employers.
  By using newer web technologies, we were able to create an immersive media-heavy site within a tight deadline that would have otherwise been impossible.
  
tags: [interactive, development]