title: Facebook, Inc.
year: 2014

description: |

  Most recently, we had
  
  The work consisted of everything from helping establish style guides and navigational paradigms to rethinking the object model.
  
  
tags:
  - internship
  - product design